CREATE TABLE `receitas_crescimento` (
	`id` int AUTO_INCREMENT NOT NULL,
	`nome` varchar(256) NOT NULL,
	`variedadeId` int NOT NULL,
	`metodoColheita` varchar(32) NOT NULL DEFAULT 'corte_unico',
	`diasGerminacao` int NOT NULL DEFAULT 5,
	`diasMudas` int NOT NULL DEFAULT 14,
	`diasVegetativa` int NOT NULL DEFAULT 21,
	`diasMaturacao` int NOT NULL DEFAULT 28,
	`ecPorFase` json,
	`phPorFase` json,
	`temperaturaMin` float,
	`temperaturaMax` float,
	`umidadeMin` float,
	`umidadeMax` float,
	`horasLuz` int,
	`densidadePorPerfil` int,
	`yieldEsperadoGramas` float,
	`observacoes` text,
	`ativa` boolean NOT NULL DEFAULT true,
	`criadoPorId` int,
	`criadoPorNome` varchar(128),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `receitas_crescimento_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `registros_colheita` (
	`id` int AUTO_INCREMENT NOT NULL,
	`torreId` int NOT NULL,
	`andarId` int NOT NULL,
	`variedadeId` int,
	`variedadeNome` varchar(128),
	`receitaId` int,
	`dataColheita` timestamp NOT NULL,
	`quantidadePlantas` int NOT NULL DEFAULT 0,
	`pesoTotalGramas` float,
	`qualidade` varchar(8) DEFAULT 'B',
	`destino` varchar(256),
	`observacoes` text,
	`executadoPorId` int,
	`executadoPorNome` varchar(128),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `registros_colheita_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `tarefas` (
	`id` int AUTO_INCREMENT NOT NULL,
	`titulo` varchar(256) NOT NULL,
	`descricao` text,
	`tipo` varchar(32) NOT NULL DEFAULT 'outro',
	`prioridade` varchar(16) NOT NULL DEFAULT 'media',
	`dataVencimento` timestamp NOT NULL,
	`torreId` int,
	`andarNumero` int,
	`caixaAguaId` int,
	`cicloId` int,
	`atribuidoParaId` int,
	`atribuidoParaNome` varchar(128),
	`status` varchar(32) NOT NULL DEFAULT 'pendente',
	`concluidoPorId` int,
	`concluidoPorNome` varchar(128),
	`concluidoEm` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `tarefas_id` PRIMARY KEY(`id`)
);
