CREATE TABLE `alert_events` (
	`id` int AUTO_INCREMENT NOT NULL,
	`alertaId` int NOT NULL,
	`eventoTipo` varchar(32) NOT NULL,
	`usuarioId` int,
	`usuarioNome` varchar(128),
	`observacao` text,
	`dadosExtra` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `alert_events_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `intelligent_alerts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tipo` varchar(64) NOT NULL,
	`severidade` varchar(16) NOT NULL DEFAULT 'media',
	`prioridade` varchar(16) NOT NULL DEFAULT 'media',
	`titulo` varchar(512) NOT NULL,
	`descricao` text NOT NULL,
	`entidadeTipo` varchar(32),
	`entidadeId` int,
	`entidadeNome` varchar(256),
	`fase` varchar(32),
	`origem` varchar(64) NOT NULL DEFAULT 'motor_regras',
	`ruleId` int,
	`dadosSnapshot` json,
	`sugestaoAcao` text NOT NULL,
	`nivelConfianca` varchar(16) NOT NULL DEFAULT 'alta',
	`status` varchar(16) NOT NULL DEFAULT 'novo',
	`lidoPorId` int,
	`lidoPorNome` varchar(128),
	`resolvidoPorId` int,
	`resolvidoPorNome` varchar(128),
	`ignoradoPorId` int,
	`ignoradoPorNome` varchar(128),
	`ignoradoMotivo` text,
	`ignoradoPrazo` timestamp,
	`gerarTarefa` boolean NOT NULL DEFAULT false,
	`tarefaGeradaId` int,
	`hashUnico` varchar(128),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `intelligent_alerts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `recommendation_rules` (
	`id` int AUTO_INCREMENT NOT NULL,
	`nome` varchar(256) NOT NULL,
	`tipo` varchar(64) NOT NULL,
	`gatilho` text NOT NULL,
	`condicao` text NOT NULL,
	`acaoSugerida` text NOT NULL,
	`faseAplicavel` varchar(32),
	`prioridadePadrao` varchar(16) NOT NULL DEFAULT 'media',
	`severidadePadrao` varchar(16) NOT NULL DEFAULT 'media',
	`ativo` boolean NOT NULL DEFAULT true,
	`versao` int NOT NULL DEFAULT 1,
	`criadoPorId` int,
	`criadoPorNome` varchar(128),
	`aprovadoPorId` int,
	`aprovadoPorNome` varchar(128),
	`fonte` varchar(256),
	`observacoes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `recommendation_rules_id` PRIMARY KEY(`id`)
);
