ALTER TABLE `clientes`
  MODIFY COLUMN `tipo` ENUM('RESTAURANTE','MERCADO','PLANO_ASSINATURA','SUPERMERCADO','AVULSO','OUTROS') NOT NULL;

UPDATE `clientes`
SET `tipo` = 'SUPERMERCADO'
WHERE `tipo` = 'MERCADO';

ALTER TABLE `clientes`
  MODIFY COLUMN `tipo` ENUM('RESTAURANTE','PLANO_ASSINATURA','SUPERMERCADO','AVULSO','OUTROS') NOT NULL;
